### ISSUE TITLE
Chronos crashes at 50 registrations per second traffic load

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/chronos#195]
With release-82 a duplex deployment with a single Sprout isolated via DNS (for performance measurements) was able to handle 50 RPS to preregister subscribers. With release-85 the system goes into overload at this rate and Chronos crashes multiple times. The first call trace-back is as follows:

```
#0  0x00007fa702b73cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fa702b770d8 in __GI_abort () at abort.c:89
#2  0x000000000045cb9f in ExceptionHandler::handle_exception (this=0x1302af0)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/cpp-common/src/exception_handler.cpp:73
#3  0x00000000004930f5 in signal_handler (sig=6)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/main.cpp:150
#4  <signal handler called>
#5  0x00007fa702b73cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#6  0x00007fa702b770d8 in __GI_abort () at abort.c:89
#7  0x00007fa7032686b5 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fa703266836 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fa703266863 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fa703266aa2 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x000000000044374b in TimerStore::insert (this=0x7fa7056fb010, tp=...,
    id=548222859529420826, next_pop_time=510549466, cluster_view_id_vector=...)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/timer_store.cpp:108
#12 0x000000000043f03a in TimerHandler::add_timer (this=0x13f0530,
    timer=0x7fa6dc0741a0)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/timer_handler.cpp:254
#13 0x0000000000432152 in ControllerTask::add_or_update_timer (
    this=0x7fa6dc071e70, timer_id=548222859529420826, replica_hash=-2080243440)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/handlers.cpp:152
#14 0x0000000000431d32 in ControllerTask::run (this=0x7fa6dc071e70)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/handlers.cpp:88
#15 0x000000000049626e in HttpStackUtils::SpawningHandler<ControllerTask, ControllerTask::Config>::process_request (this=0x7ffe4cfb6f70, req=..., trail=766)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/cpp-common/include/httpstack_utils.h:79
#16 0x0000000000453b42 in HttpStack::handler_callback (
    this=0x717be0 <HttpStack::DEFAULT_INSTANCE>, req=0x7fa6dc076380,
    handler=0x7ffe4cfb6f70)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/cpp-common/src/httpstack.cpp:290
#17 0x0000000000453958 in HttpStack::handler_callback_fn (req=0x7fa6dc076380,
    handler=0x7ffe4cfb6f70)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/cpp-common/src/httpstack.cpp:256
#18 0x00000000004a4c02 in _evhtp_request_parser_fini (p=<optimized out>)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/libevhtp/evhtp.c:1354
#19 0x00000000004a8054 in hook_on_msg_complete_run (hooks=<optimized out>,
    p=<optimized out>)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/libevhtp/htparse/htparse.c:256
#20 htparser_run (p=0x7fa6b8118b10,
    hooks=hooks@entry=0x716dc0 <request_psets>,
    data=data@entry=0x7fa6dc0715a0 "PUT /timers/079badc94000001a0348002584020110 HTTP/1.1\r\nHost: 192.168.140.195:7253\r\nAccept: */*\r\nContent-Length: 283\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n{\"timing\":{\"start-time\":28394886"..., len=len@entry=451)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/libevhtp/htparse/htparse.c:1849
#21 0x00000000004a62d6 in _evhtp_connection_readcb (bev=0x7fa6dc082350,
    arg=0x7fa6b80d8590)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/libevhtp/evhtp.c:1514
#22 0x00007fa704c7b7ca in ?? ()
   from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#23 0x00007fa704c70f24 in event_base_loop ()
   from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#24 0x00000000004a9242 in _evthr_loop (args=0x1434100)
    at /var/build/CC_9.0.0-WIP/cc/chronos/modules/libevhtp/evthr/evthr.c:196
#25 0x00007fa705116182 in start_thread (arg=0x7fa66af7d700)
    at pthread_create.c:312
#26 0x00007fa702c3747d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

The second call trace-back is as follows:

```
#0  0x00007fa702b73cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fa702b73cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fa702b770d8 in __GI_abort () at abort.c:89
#2  0x0000000000493116 in signal_handler (sig=11) at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/main.cpp:156
#3  <signal handler called>
#4  0x000000000041be98 in std::less<unsigned long>::operator() (this=0x7fa7056fb018,
    __x=@0x300000022: <error reading variable>, __y=@0x7fa6d4097c60: 548223498405806107)
    at /usr/include/c++/4.8/bits/stl_function.h:235
#5  0x000000000044881c in std::_Rb_tree<unsigned long, std::pair<unsigned long const, TimerPair>, std::_Select1st<std::pair<unsigned long const, TimerPair> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, TimerPair> > >::_M_lower_bound (this=0x7fa7056fb018, __x=0x300000002, __y=0x7fa6d4072960,
    __k=@0x7fa6d4097c60: 548223498405806107) at /usr/include/c++/4.8/bits/stl_tree.h:1141
#6  0x0000000000449a49 in std::_Rb_tree<unsigned long, std::pair<unsigned long const, TimerPair>, std::_Select1st<std::pair<unsigned long const, TimerPair> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, TimerPair> > >::equal_range (this=0x7fa7056fb018, __k=@0x7fa6d4097c60: 548223498405806107)
    at /usr/include/c++/4.8/bits/stl_tree.h:1220
#7  0x0000000000447c99 in std::_Rb_tree<unsigned long, std::pair<unsigned long const, TimerPair>, std::_Select1st<std::pair<unsigned long const, TimerPair> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, TimerPair> > >::erase (this=0x7fa7056fb018, __x=@0x7fa6d4097c60: 548223498405806107)
    at /usr/include/c++/4.8/bits/stl_tree.h:1769
#8  0x0000000000446a05 in std::map<unsigned long, TimerPair, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, TimerPair> > >::erase (this=0x7fa7056fb018, __x=@0x7fa6d4097c60: 548223498405806107)
    at /usr/include/c++/4.8/bits/stl_map.h:727
#9  0x0000000000443e72 in TimerStore::pop_bucket (this=0x7fa7056fb010, bucket=0x7fa7056fc340, set=...)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/timer_store.cpp:281
#10 0x0000000000443c06 in TimerStore::fetch_next_timers (this=0x7fa7056fb010, set=...)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/timer_store.cpp:206
#11 0x0000000000440118 in TimerHandler::run (this=0x13f0530)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/timer_handler.cpp:544
#12 0x000000000043e600 in TimerHandler::timer_handler_entry_func (arg=0x13f0530)
    at /var/build/CC_9.0.0-WIP/cc/chronos/src/main/timer_handler.cpp:49
#13 0x00007fa705116182 in start_thread (arg=0x7fa68b7be700) at pthread_create.c:312
#14 0x00007fa702c3747d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Diagnostics will be uploaded.

**Comment by mirw** [comment]
@bossmc, have you seen anything like this in your recent work in this area?

**Comment by rkd-msw** [comment]
@plfrancis , two questions:

- does this reproduce consistently for you, or is this a one-off? I've successfully run 20,000 registrations at 150 registrations/second through a Sprout node, without Chronos crashing - I'm wondering if this suggests the issue is fixed in the very latest code, or if I've just got lucky (or if my test - REGISTER, 401, REGISTER, 200 - doesn't match yours)
- you mention release-82 and release-85 - what precise code is that? I ask because the code tagged release-82 and release-85 in Github is the same commit, 3bb5210 (due to code coverage regressions, we haven't promoted the Chronos dev branch to master recently)

**Comment by rkd-msw** [comment]
And a third question: what is your registration expiry interval for these tests? (This affects the timers set in Chronos, so might change the behaviour.)

**Comment by plfrancis** [comment]
@rkd-msw, three answers:

* I tried it twice and observed the crashes both times.
* We used the release-82 tag as the base for CC v8, and have recently built an initial CC v9 load based on the release-85 tag. This behavior was not observed in v8 but now exists in v9. It apparently may not be due to changes in Chronos itself based upon your comment.
* That is an interesting question. Due to the nature of IMS Bench a large number of subscribers need to be pre-registered, and stay registered for the duration of the test. In order to support long traffic runs I set the registration expiry interval to 1 week. But, the same value was used for both v8 and v9 tests.

**Comment by rkd-msw** [comment]
Regarding the CCv9 build based on release-85, is the code for that on Github? If https://github.com/ClearwaterCore/chronos/commit/102e2a0a0a6c2ab99e22c6f287b02cd780ffc8d1 hadn't been back-applied (e.g. because you assumed it was already in the newer code), that would explain this problem - but I can't see an appropriate branch I can check to prove/disprove that hypothesis.

**Comment by plfrancis** [comment]
Hypothesis correct. I checked with @dtheobald and he confirmed that the cited commit had not been back-applied for the initial CC v9 load. The assumption was that any critical commit explicitly included in a CC load would have been applied to the next PC load (and in this case two subsequent loads beyond that). 

In the immortal words of Robert Plant... "Communication Breakdown, It's always the same,
I'm having a nervous breakdown, Drive me insane!"... closing.
