### ISSUE TITLE
Chronos crashes on stop

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/chronos#254]
#### Symptoms
Chronos crashes when it's stopped (looks like an alarms issue).

```
Thread 2 (Thread 0x7f2e64617700 (LWP 4821)):
#0  0x00007f2e6b8bcb99 in __libc_waitpid (pid=5077, stat_loc=stat_loc@entry=0x7f2e646142e0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007f2e6b8422e2 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x0000000000447b13 in Logger::backtrace (this=0x204aa20, data=<optimized out>) at ../modules/cpp-common/src/logger.cpp:318
#3  0x00000000004475dd in Log::backtrace (fmt=fmt@entry=0x4b60c8 "Signal %d caught") at ../modules/cpp-common/src/log.cpp:185
#4  0x000000000047b5fc in signal_handler (sig=6) at main.cpp:161
#5  <signal handler called>
#6  0x00007f2e6b832cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#7  0x00007f2e6b8360d8 in __GI_abort () at abort.c:89
#8  0x00007f2e6bf27535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f2e6bf256d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f2e6bf25703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f2e6bf25976 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x000000000041f2a1 in std::vector<std::string, std::allocator<std::string> >::_M_emplace_back_aux<std::string const&> (this=0x7f2e64616e00) at /usr/include/c++/4.8/bits/vector.tcc:426
#13 0x000000000044affd in push_back (__x="chronos\000\060\000\000\000\000\000\000\000@", '\000' <repeats 15 times>, "\272\v\000\000\000\000\000\000\250\020\006\002\000\000\000\000x\021\006\002\000\000\000\000\320\020\006\002\000\000\000\000\250\020\006\002\000\000\000\000p\000\000\000\000\000\000\000 \000\000\000\000\000\000\000 \021\006\002\000\000\000\000\200\022\006\002\000\000\000\000\377\377\377\377\000\000\000\000A\000\000\000\000\000\000\000\020\025\006\002\000\000\000\000\000\020\006\002\000\000\000\000\070\021\006\002\000\000\000\000passwd\000\000\377\377\377\377\000\000\000\000\063\060\060\062\000\000\000\000@\000\000\000\000\000\000\000\061\000\000\000\000\000\000\000\v\000\000\000\000\000\000\000\v\000\000\000\000\000\000\000"..., this=0x7f2e64616e00) at /usr/include/c++/4.8/bits/stl_vector.h:911
#14 AlarmState::issue (this=0x20610d0) at ../modules/cpp-common/src/alarm.cpp:69
#15 0x000000000044b2d2 in reraise_last_state (this=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:103
#16 AlarmManager::reraise_alarms (this=0x2061190) at ../modules/cpp-common/src/alarm.cpp:257
#17 0x000000000044b3b9 in AlarmManager::reraise_alarms_function (data=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:225
#18 0x00007f2e6ddd5182 in start_thread (arg=0x7f2e64617700) at pthread_create.c:312
#19 0x00007f2e6b8f647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by eleanor-merry** [comment]
This isn't in release-94-fixes
